FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libffi-dev libpango-1.0-0 libpangoft2-1.0-0 libjpeg62-turbo && rm -rf /var/lib/apt/lists/*
COPY forecasting /deps/forecasting
RUN pip install /deps/forecasting
COPY backend /app
RUN pip install -e .
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
