"""Add forecast fields and realisasi table

Revision ID: 0002_add_forecast_fields
Revises: 0001_init
Create Date: 2025-08-25 23:03:48.964769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_add_forecast_fields'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realisasi_tahunan',
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('jenis_pajak', sa.String(length=16), nullable=False),
    sa.Column('nilai', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('tahun', 'jenis_pajak')
    )
    op.add_column('forecast_run', sa.Column('meta_json', sa.Text(), nullable=True))
    op.add_column('forecast_result', sa.Column('p10', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('forecast_result', sa.Column('p50', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('forecast_result', sa.Column('p90', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_result', 'p90')
    op.drop_column('forecast_result', 'p50')
    op.drop_column('forecast_result', 'p10')
    op.drop_column('forecast_run', 'meta_json')
    op.drop_table('realisasi_tahunan')
    # ### end Alembic commands ###
